### ISSUE TITLE
Supporter Update

### ISSUE THREAD

**Issue by adibender** [lmu-applied-r/lmu-applied-r.github.io#2]
Wir sollten auch hier die Supporter updaten, 
z.B. dieses Enterpreneurship Center dasss das letzte Treffen gesponsort hatte.

Oder ist hier mit "Supporter" was anderes gemeint?

**Comment by berndbischl** [comment]
Nein, das hast du schon korrekt verstanden.

Und ja wir sollten hier umschauend und korrekt sein. Wer was gibt wird auch genannt

**Comment by philippstats** [comment]
Meta-Frage: Brauchen wir eigentlich noch eine github homepage, wenn wir alles (!) über meetup regeln können und auch wollen (mitgliedschaften, rsvp, mails, diskussionen, sponsoren-erwähnung)?

**Comment by berndbischl** [comment]
Für mich war die Homepage "Außendarstellung".
Und sie sieht halt etwas schöner aus, finde ich.

Ich wusste allerdings nicht dass die Meetup-Seite so "reichhaltig" ist.
Da kann man ja noch Unterseiten anlegen, Files hosten, usw.

Wahrscheinlich ist es doch besser, sich auf eine Sache zu konzentrieren, statt Arbeit doppelt zu machen.
Sollten wir vielleicht beim nächsten Treffen entscheiden.

**Comment by philippstats** [comment]
Seite ist wieder up-to-date. 
Am 25.4. drüber reden find ich gut :)
